In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/airbnbopendata/Airbnb_Open_Data.csv

In [2]:

pd.set_option('display.max_columns', 30)

In [3]:
import pandas as pd
import numpy as np

# Dataframe original
df_original = pd.read_csv('/kaggle/input/airbnbopendata/Airbnb_Open_Data.csv', low_memory=False)
# Vamos fazer uma cópia para trabalharmos
df = df_original.copy()
df.head(10)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2015.0,$71,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,strict,Private room,2005.0,"$1,018",$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,strict,Private room,2015.0,$291,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN

Drop the last column as it doesnt contain anything.

In [4]:
df.drop('license', axis=1,inplace = True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
dtypes: float64(9), int64(2), object(14)
memory usage: 19.6+ MB

Treat missing values. I will assume that column 21 is important to keep. So I will subset the dataset based on nonnull values from this column

In [6]:
df = df[df['review rate number'].notnull()]

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102273 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102273 non-null  int64
 1   NAME                            102031 non-null  object
 2   host id                         102273 non-null  int64
 3   host_identity_verified          101998 non-null  object
 4   host name                       101874 non-null  object
 5   neighbourhood group             102246 non-null  object
 6   neighbourhood                   102257 non-null  object
 7   lat                             102265 non-null  float64
 8   long                            102265 non-null  float64
 9   country                         101741 non-null  object
 10  country code                    102156 non-null  object
 11  instant_bookable                102182 non-null  object
 12  cancellation_policy             102197 non-null  object
 13  room type                       102273 non-null  object
 14  Construction year               102067 non-null  float64
 15  price                           102026 non-null  object
 16  service fee                     102000 non-null  object
 17  minimum nights                  101884 non-null  float64
 18  number of reviews               102091 non-null  float64
 19  last review                     86418 non-null   object
 20  reviews per month               86432 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102022 non-null  float64
 23  availability 365                101839 non-null  float64
 24  house_rules                     50308 non-null   object
dtypes: float64(9), int64(2), object(14)
memory usage: 20.3+ MB

Change data type

In [7]:

df['Construction year'] = pd.to_datetime(df['Construction year'], format='%Y', errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102273 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102273 non-null  int64
 1   NAME                            102031 non-null  object
 2   host id                         102273 non-null  int64
 3   host_identity_verified          101998 non-null  object
 4   host name                       101874 non-null  object
 5   neighbourhood group             102246 non-null  object
 6   neighbourhood                   102257 non-null  object
 7   lat                             102265 non-null  float64
 8   long                            102265 non-null  float64
 9   country                         101741 non-null  object
 10  country code                    102156 non-null  object
 11  instant_bookable                102182 non-null  object
 12  cancellation_policy             102197 non-null  object
 13  room type                       102273 non-null  object
 14  Construction year               102067 non-null  datetime64[ns]
 15  price                           102026 non-null  object
 16  service fee                     102000 non-null  object
 17  minimum nights                  101884 non-null  float64
 18  number of reviews               102091 non-null  float64
 19  last review                     86418 non-null   object
 20  reviews per month               86432 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102022 non-null  float64
 23  availability 365                101839 non-null  float64
 24  house_rules                     50308 non-null   object
dtypes: datetime64[ns](1), float64(8), int64(2), object(14)
memory usage: 20.3+ MB

Clean up the price columns which contain strings

In [8]:
# Check the current datatype 
df['price'].dtypes

dtype('O')

In [9]:
# Check the current datatype 
df['service fee'].dtypes

dtype('O')

In [10]:
# This function will remove the '$' and ',' from each individual element of the column and return float(x) or np.nan (for nan values)

def clean_column(x):
    try:
        x = x.replace('$', '')
        x = x.replace(',', '')
        return float(x)
    except:
        return np.nan

df['price'] = df['price'].apply(clean_column)

In [11]:
df['service fee'] = df['service fee'].apply(clean_column)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102273 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102273 non-null  int64
 1   NAME                            102031 non-null  object
 2   host id                         102273 non-null  int64
 3   host_identity_verified          101998 non-null  object
 4   host name                       101874 non-null  object
 5   neighbourhood group             102246 non-null  object
 6   neighbourhood                   102257 non-null  object
 7   lat                             102265 non-null  float64
 8   long                            102265 non-null  float64
 9   country                         101741 non-null  object
 10  country code                    102156 non-null  object
 11  instant_bookable                102182 non-null  object
 12  cancellation_policy             102197 non-null  object
 13  room type                       102273 non-null  object
 14  Construction year               102067 non-null  datetime64[ns]
 15  price                           102026 non-null  float64
 16  service fee                     102000 non-null  float64
 17  minimum nights                  101884 non-null  float64
 18  number of reviews               102091 non-null  float64
 19  last review                     86418 non-null   object
 20  reviews per month               86432 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102022 non-null  float64
 23  availability 365                101839 non-null  float64
 24  house_rules                     50308 non-null   object
dtypes: datetime64[ns](1), float64(10), int64(2), object(12)
memory usage: 20.3+ MB

Check incorrect values in 'availabilty 365'

In [13]:
df[df['availability 365'] > 365]

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013-01-01,577.0,115.0,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs."
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,strict,Private room,2015-01-01,291.0,58.0,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....
25,1015144,"MAISON DES SIRENES1,bohemian apartment",48387947293,NaN,Miranda,Brooklyn,Bedford-Stuyvesant,40.68371,-73.94028,United States,NaN,NaN,strict,Entire home/apt,2006-01-01,1175.0,235.0,2.0,88.0,6/19/2019,0.73,4.0,2.0,372.0,NaN
43,1025085,1bdr w private bath. in lofty apt,45597582469,NaN,Charlie,Brooklyn,Fort Greene,40.69673,-73.97584,United States,US,False,strict,Private room,2008-01-01,687.0,137.0,7.0,25.0,9/30/2018,0.23,1.0,1.0,405.0,"No smoking, No pets. No shoes in the house. Vi..."
110,1062089,Sunny 2-story Brooklyn townhouse w deck and ga...,85201462079,verified,Alen,Brooklyn,Gowanus,40.68157,-73.98989,United States,US,False,strict,Entire home/apt,2011-01-01,528.0,106.0,30.0,19.0,3/17/2017,0.20,2.0,1.0,400.0,We ask that guest DO NOT host any additional g...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102582,6085810,Private room in the best part of BK,4746552394,verified,Brad,Brooklyn,Crown Heights,40.66743,-73.94712,United States,US,False,flexible,Private room,2011-01-01,516.0,103.0,7.0,49.0,6/1/2019,1.01,2.0,1.0,425.0,No Smoking. Pets Allowed with fee.
102584,6086914,2 block walk from the beach in NYC,70051719594,verified,Vladimir,Queens,Arverne,40.59270,-73.78990,United States,US,False,strict,Entire home/apt,2010-01-01,566.0,113.0,2.0,89.0,5/26/2019,1.82,2.0,1.0,394.0,NaN
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,US,True,flexible,Entire home/apt,2016-01-01,618.0,124.0,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016-01-01,837.0,167.0,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015-01-01,546.0,109.0,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN

In [14]:
# Remove outliers from the dataset
cleaned_df = df[df['availability 365'] < 365]

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)

In [15]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96578 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              96578 non-null  int64
 1   NAME                            96362 non-null  object
 2   host id                         96578 non-null  int64
 3   host_identity_verified          96323 non-null  object
 4   host name                       96201 non-null  object
 5   neighbourhood group             96563 non-null  object
 6   neighbourhood                   96565 non-null  object
 7   lat                             96570 non-null  float64
 8   long                            96570 non-null  float64
 9   country                         96088 non-null  object
 10  country code                    96480 non-null  object
 11  instant_bookable                96506 non-null  object
 12  cancellation_policy             96520 non-null  object
 13  room type                       96578 non-null  object
 14  Construction year               96409 non-null  datetime64[ns]
 15  price                           96345 non-null  float64
 16  service fee                     96319 non-null  float64
 17  minimum nights                  96230 non-null  float64
 18  number of reviews               96457 non-null  float64
 19  last review                     82109 non-null  object
 20  reviews per month               82108 non-null  float64
 21  review rate number              96578 non-null  float64
 22  calculated host listings count  96363 non-null  float64
 23  availability 365                96578 non-null  float64
 24  house_rules                     47335 non-null  object
dtypes: datetime64[ns](1), float64(10), int64(2), object(12)
memory usage: 19.2+ MB